I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    $ is_down = false
  File "game/script.rpy", line 27, in script
    $ is_down = false
  File "game/script.rpy", line 27, in <module>
    $ is_down = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/exiel/renpy-7.4.11-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/home/exiel/renpy-7.4.11-sdk/renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 27, in script
    $ is_down = false
  File "game/script.rpy", line 27, in script
    $ is_down = false
  File "/home/exiel/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/exiel/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 27, in <module>
    $ is_down = false
NameError: name 'false' is not defined

Linux-5.17.6-1-MANJARO-x86_64-with-glibc2.2.5
Ren'Py 7.4.11.2266
60 Seconde pour Survivre Xavier 1.0
Sat May 21 11:54:41 2022
